
# Humaiyon Abdullah

# Step - 1

In [145]:
import tkinter as tk
from tkinter import filedialog
from PIL import Image, ImageTk
import os

class ImageViewerApp:
    def __init__(self, root):
        self.root = root
        self.root.title("Image Viewer")
        
        # Frame for buttons
        self.frame = tk.Frame(root)
        self.frame.pack(side=tk.TOP, fill=tk.X)
        
        self.load_ref_button = tk.Button(self.frame, text="Load Reference Image", command=self.load_reference)
        self.load_ref_button.pack(side=tk.LEFT, padx=5, pady=5)
        
        self.load_aerial_button = tk.Button(self.frame, text="Load Aerial Images", command=self.load_aerial)
        self.load_aerial_button.pack(side=tk.LEFT, padx=5, pady=5)
        
        self.next_button = tk.Button(self.frame, text="Next", command=self.next_image, state=tk.DISABLED)
        self.next_button.pack(side=tk.RIGHT, padx=5, pady=5)
        
        self.prev_button = tk.Button(self.frame, text="Previous", command=self.prev_image, state=tk.DISABLED)
        self.prev_button.pack(side=tk.RIGHT, padx=5, pady=5)
        
        # Label for displaying images
        self.image_label = tk.Label(root)
        self.image_label.pack(pady=10)
        
        self.ref_image = None
        self.aerial_images = []
        self.current_index = 0
    
    def load_reference(self):
        filepath = filedialog.askopenfilename(filetypes=[("TIFF files", "*.tif"), ("All files", "*.*")])
        if filepath:
            self.ref_image = self.load_image(filepath)
            self.display_image(self.ref_image)
    
    def load_aerial(self):
        filepaths = filedialog.askopenfilenames(filetypes=[("PNG files", "*.png"), ("All files", "*.*")])
        if filepaths:
            self.aerial_images = [self.load_image(fp) for fp in filepaths]
            self.current_index = 0
            self.display_image(self.aerial_images[0])
            self.update_buttons()
    
    def load_image(self, path):
        img = Image.open(path)
        img = img.resize((600, 400), Image.LANCZOS)  # Resize for display
        return ImageTk.PhotoImage(img)
    
    def display_image(self, img):
        self.image_label.config(image=img)
        self.image_label.image = img
    
    def next_image(self):
        if self.current_index < len(self.aerial_images) - 1:
            self.current_index += 1
            self.display_image(self.aerial_images[self.current_index])
        self.update_buttons()
    
    def prev_image(self):
        if self.current_index > 0:
            self.current_index -= 1
            self.display_image(self.aerial_images[self.current_index])
        self.update_buttons()
    
    def update_buttons(self):
        self.prev_button.config(state=tk.NORMAL if self.current_index > 0 else tk.DISABLED)
        self.next_button.config(state=tk.NORMAL if self.current_index < len(self.aerial_images) - 1 else tk.DISABLED)

if __name__ == "__main__":
    root = tk.Tk()
    app = ImageViewerApp(root)
    root.mainloop()

# Step - 2

In [10]:
import tkinter as tk
from tkinter import filedialog
from PIL import Image, ImageTk

class ImageViewer:
    def __init__(self, root):
        self.root = root
        self.root.title("Image Viewer")

        # Frame for buttons
        self.frame = tk.Frame(root)
        self.frame.pack()

        # Buttons
        self.load_ref_button = tk.Button(self.frame, text="Load Reference Image", command=self.load_reference_image)
        self.load_ref_button.pack(side=tk.LEFT)

        self.load_aerial_button = tk.Button(self.frame, text="Load Aerial Images", command=self.load_aerial_images)
        self.load_aerial_button.pack(side=tk.LEFT)

        self.prev_button = tk.Button(self.frame, text="Previous", command=self.show_previous, state=tk.DISABLED)
        self.prev_button.pack(side=tk.LEFT)

        self.next_button = tk.Button(self.frame, text="Next", command=self.show_next, state=tk.DISABLED)
        self.next_button.pack(side=tk.LEFT)

        # Canvas to display images
        self.canvas = tk.Canvas(root, width=800, height=600, bg="gray")
        self.canvas.pack()

        # Image variables
        self.reference_image = None
        self.aerial_images = []
        self.current_index = 0

        # Click event
        self.canvas.bind("<Button-1>", self.get_pixel_coordinates)

    def load_reference_image(self):
        filepath = filedialog.askopenfilename(filetypes=[("TIFF files", "*.tif"), ("All files", "*.*")])
        if filepath:
            self.reference_image = Image.open(filepath)
            self.display_image(self.reference_image)

    def load_aerial_images(self):
        filepaths = filedialog.askopenfilenames(filetypes=[("PNG files", "*.png"), ("All files", "*.*")])
        if filepaths:
            self.aerial_images = [Image.open(fp) for fp in filepaths]
            self.current_index = 0
            self.display_image(self.aerial_images[self.current_index])
            self.update_buttons()

    def display_image(self, image):
        """ Resizes and displays an image on the canvas """
        image = image.resize((800, 600), Image.Resampling.LANCZOS)
        self.tk_image = ImageTk.PhotoImage(image)
        self.canvas.create_image(0, 0, anchor=tk.NW, image=self.tk_image)

    def show_previous(self):
        if self.current_index > 0:
            self.current_index -= 1
            self.display_image(self.aerial_images[self.current_index])
            self.update_buttons()

    def show_next(self):
        if self.current_index < len(self.aerial_images) - 1:
            self.current_index += 1
            self.display_image(self.aerial_images[self.current_index])
            self.update_buttons()

    def update_buttons(self):
        """ Enable/Disable navigation buttons based on index """
        self.prev_button.config(state=tk.NORMAL if self.current_index > 0 else tk.DISABLED)
        self.next_button.config(state=tk.NORMAL if self.current_index < len(self.aerial_images) - 1 else tk.DISABLED)

    def get_pixel_coordinates(self, event):
        """ Get (X, Y) coordinates of a clicked pixel and save them """
        x, y = event.x, event.y
        print(f"Clicked at: ({x}, {y})")
        with open("coordinates.txt", "a") as f:
            f.write(f"{x}, {y}\n")

# Run the application
root = tk.Tk()
app = ImageViewer(root)
root.mainloop()


Clicked at: (384, 270)
Clicked at: (438, 285)


# Step - 3

In [148]:
import cv2
import numpy as np
import tkinter as tk
from tkinter import filedialog, ttk
from PIL import Image, ImageTk

class ImageProcessor:
    def __init__(self, root):
        self.root = root
        self.root.title("Feature Detection Viewer")

        # Frame for buttons
        self.frame = tk.Frame(root)
        self.frame.pack()

        # Buttons
        self.load_ref_button = tk.Button(self.frame, text="Load Reference Image", command=self.load_reference_image)
        self.load_ref_button.pack(side=tk.LEFT)

        self.load_aerial_button = tk.Button(self.frame, text="Load Aerial Image", command=self.load_aerial_image)
        self.load_aerial_button.pack(side=tk.LEFT)

        self.compute_features_button = tk.Button(self.frame, text="Compute Features", command=self.compute_features, state=tk.DISABLED)
        self.compute_features_button.pack(side=tk.LEFT)

        # Dropdown to select feature detector
        self.detector_label = tk.Label(self.frame, text="Feature Detector:")
        self.detector_label.pack(side=tk.LEFT)

        self.detector_var = tk.StringVar(value="SIFT")  # Default to SIFT
        self.detector_dropdown = ttk.Combobox(self.frame, textvariable=self.detector_var, values=["SIFT", "ORB"])
        self.detector_dropdown.pack(side=tk.LEFT)

        # Canvas to display images
        self.canvas = tk.Canvas(root, width=800, height=600, bg="gray")
        self.canvas.pack()

        # Image variables
        self.reference_image = None
        self.aerial_image = None
        self.reference_keypoints = None
        self.reference_descriptors = None

    def get_feature_detector(self):
        """Returns the feature detector and descriptor based on user selection"""
        detector_name = self.detector_var.get()

        if detector_name == "SIFT":
            return cv2.SIFT_create()
        elif detector_name == "ORB":
            return cv2.ORB_create()
        else:
            raise ValueError("Unsupported feature detector")

    def load_reference_image(self):
        filepath = filedialog.askopenfilename(filetypes=[("TIFF files", "*.tif"), ("All files", "*.*")])
        if filepath:
            self.reference_image = cv2.imread(filepath, cv2.IMREAD_GRAYSCALE)
            self.display_image(self.reference_image)

    def load_aerial_image(self):
        filepath = filedialog.askopenfilename(filetypes=[("PNG files", "*.png"), ("All files", "*.*")])
        if filepath:
            self.aerial_image = cv2.imread(filepath, cv2.IMREAD_GRAYSCALE)
            self.display_image(self.aerial_image)
            self.compute_features_button.config(state=tk.NORMAL)  # Enable Compute Features button

    def compute_features(self):
        if self.aerial_image is None or self.reference_image is None:
            print("Please load both images first.")
            return

        # Get selected feature detector
        detector = self.get_feature_detector()

        # Compute keypoints & descriptors for reference image
        self.reference_keypoints, self.reference_descriptors = detector.detectAndCompute(self.reference_image, None)

        # Compute keypoints & descriptors for aerial image
        aerial_keypoints, aerial_descriptors = detector.detectAndCompute(self.aerial_image, None)

        # Draw keypoints on images
        ref_keypoint_img = cv2.drawKeypoints(self.reference_image, self.reference_keypoints, None, color=(0, 255, 0))
        aerial_keypoint_img = cv2.drawKeypoints(self.aerial_image, aerial_keypoints, None, color=(0, 255, 0))

        # Resize images to the same height
        ref_height, ref_width = ref_keypoint_img.shape[:2]
        aerial_height, aerial_width = aerial_keypoint_img.shape[:2]

        if ref_height != aerial_height:
            new_width = int(aerial_width * (ref_height / aerial_height))
            aerial_keypoint_img = cv2.resize(aerial_keypoint_img, (new_width, ref_height))

        # Ensure both images have the same number of channels
        if len(ref_keypoint_img.shape) == 2:  # Grayscale
            ref_keypoint_img = cv2.cvtColor(ref_keypoint_img, cv2.COLOR_GRAY2BGR)
        if len(aerial_keypoint_img.shape) == 2:
            aerial_keypoint_img = cv2.cvtColor(aerial_keypoint_img, cv2.COLOR_GRAY2BGR)

        # Stack images horizontally
        stacked_img = np.hstack((ref_keypoint_img, aerial_keypoint_img))
        self.display_image(stacked_img)

    def display_image(self, image):
        """ Convert OpenCV image to Tkinter-compatible format and display it """
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB) if len(image.shape) == 3 else cv2.cvtColor(image, cv2.COLOR_GRAY2RGB)
        image = Image.fromarray(image)
        image = image.resize((800, 600), Image.Resampling.LANCZOS)
        self.tk_image = ImageTk.PhotoImage(image)
        self.canvas.create_image(0, 0, anchor=tk.NW, image=self.tk_image)

# Run the application
root = tk.Tk()
app = ImageProcessor(root)
root.mainloop()


# Step - 4

In [155]:
import cv2
import numpy as np
import pickle
import os
import tkinter as tk
from tkinter import filedialog
from PIL import Image, ImageTk

class ImageProcessor:
    def __init__(self, root):
        self.root = root
        self.root.title("Feature Matching & Homography")

        # Frame for buttons
        self.frame = tk.Frame(root)
        self.frame.pack()

        # Buttons
        self.load_ref_button = tk.Button(self.frame, text="Load Reference Image", command=self.load_reference_image)
        self.load_ref_button.pack(side=tk.LEFT)

        self.load_aerial_button = tk.Button(self.frame, text="Load Aerial Image", command=self.load_aerial_image)
        self.load_aerial_button.pack(side=tk.LEFT)

        self.compute_homography_button = tk.Button(self.frame, text="Compute Homography", command=self.compute_homography, state=tk.DISABLED)
        self.compute_homography_button.pack(side=tk.LEFT)

        # Canvas to display images
        self.canvas = tk.Canvas(root, width=800, height=600, bg="gray")
        self.canvas.pack()

        # Image variables
        self.reference_image = None
        self.aerial_image = None
        self.reference_keypoints = None
        self.reference_descriptors = None
        self.orb = cv2.ORB_create()

    def load_reference_image(self):
        filepath = filedialog.askopenfilename(filetypes=[("TIFF files", "*.tif"), ("All files", "*.*")])
        if filepath:
            self.reference_image = cv2.imread(filepath, cv2.IMREAD_GRAYSCALE)
            self.display_image(self.reference_image)

            # Try loading precomputed keypoints and descriptors
            if os.path.exists("reference_features.pkl"):
                try:
                    with open("reference_features.pkl", "rb") as f:
                        data = pickle.load(f)
                        self.reference_keypoints = [cv2.KeyPoint(x, y, size) for x, y, size in data["keypoints"]]
                        self.reference_descriptors = data["descriptors"]
                    print("Loaded precomputed reference features.")
                    return
                except (EOFError, pickle.UnpicklingError):
                    print("Corrupted feature file detected. Recomputing...")

            # Compute and store features
            self.reference_keypoints, self.reference_descriptors = self.orb.detectAndCompute(self.reference_image, None)
            keypoints_serializable = [(kp.pt[0], kp.pt[1], kp.size) for kp in self.reference_keypoints]
            data = {"keypoints": keypoints_serializable, "descriptors": self.reference_descriptors}

            with open("reference_features.pkl", "wb") as f:
                pickle.dump(data, f)
            print("Computed and stored new reference features.")

    def load_aerial_image(self):
        filepath = filedialog.askopenfilename(filetypes=[("PNG files", "*.png"), ("All files", "*.*")])
        if filepath:
            aerial_img = cv2.imread(filepath, cv2.IMREAD_GRAYSCALE)
    
            # Resize aerial image to match reference image size
            if self.reference_image is not None:
                aerial_img = cv2.resize(aerial_img, (self.reference_image.shape[1], self.reference_image.shape[0]))
    
            self.aerial_image = aerial_img
            self.display_image(self.aerial_image)
            self.compute_homography_button.config(state=tk.NORMAL)  # Enable Compute Homography button

    
    def compute_homography(self):
        if self.aerial_image is None or self.reference_image is None:
            print("Please load both images first.")
            return
    
        # Compute keypoints & descriptors for aerial image
        aerial_keypoints, aerial_descriptors = self.orb.detectAndCompute(self.aerial_image, None)
    
        # Match descriptors using BFMatcher
        bf = cv2.BFMatcher(cv2.NORM_HAMMING, crossCheck=True)
        matches = bf.match(self.reference_descriptors, aerial_descriptors)
        matches = sorted(matches, key=lambda x: x.distance)  # Sort matches by distance
    
        # Use top N matches
        num_matches = 55  # Adjust as needed
        good_matches = matches[:num_matches]
    
        if len(good_matches) < 4:
            print("Not enough matches to compute homography.")
            return
    
        # Extract matched keypoints
        ref_pts = np.float32([self.reference_keypoints[m.queryIdx].pt for m in good_matches]).reshape(-1, 1, 2)
        aerial_pts = np.float32([aerial_keypoints[m.trainIdx].pt for m in good_matches]).reshape(-1, 1, 2)
    
        # Compute Homography using RANSAC
        H, mask = cv2.findHomography(aerial_pts, ref_pts, cv2.RANSAC, 15.0)
        H /= H[2, 2]  # Normalize
        print("Computed Homography Matrix:\n", H)    
        print("Determinant of Normalized H:", np.linalg.det(H))

        # Draw matches
        match_img = cv2.drawMatches(self.reference_image, self.reference_keypoints,
                                    self.aerial_image, aerial_keypoints,
                                    good_matches, None, flags=cv2.DrawMatchesFlags_NOT_DRAW_SINGLE_POINTS)
    
        # Resize images to the same height before stacking
        ref_height, ref_width = self.reference_image.shape[:2]
        aerial_height, aerial_width = self.aerial_image.shape[:2]
    
        if ref_height != aerial_height:
            new_width = int(aerial_width * (ref_height / aerial_height))  # Maintain aspect ratio
            match_img = cv2.resize(match_img, (new_width + ref_width, ref_height))
    
        # Display image
        self.display_image(match_img)
        self.H = H  # Store homography for later use


    def project_point(self, x, y):
        """ Projects a pixel from aerial image to reference image using Homography matrix """
        if not hasattr(self, 'H') or self.H is None:
            print("Homography matrix not computed yet.")
            return None

        point = np.array([[x, y, 1]], dtype=np.float32).T  # Convert to homogeneous coordinates
        projected_point = np.dot(self.H, point)
        projected_point /= projected_point[2]  # Normalize

        return int(projected_point[0]), int(projected_point[1])  # Return (X, Y) in reference image

    def display_image(self, image):
        """ Convert OpenCV image to Tkinter-compatible format and display it """
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB) if len(image.shape) == 3 else cv2.cvtColor(image, cv2.COLOR_GRAY2RGB)
        image = Image.fromarray(image)
        image = image.resize((800, 600), Image.Resampling.LANCZOS)
        self.tk_image = ImageTk.PhotoImage(image)
        self.canvas.create_image(0, 0, anchor=tk.NW, image=self.tk_image)

# Run the application
root = tk.Tk()
app = ImageProcessor(root)
root.mainloop()


Loaded precomputed reference features.
Computed Homography Matrix:
 [[-3.80945165e+00  1.21105820e+00  3.50819106e+03]
 [-1.30932808e+00  2.72054071e-01  1.69410617e+03]
 [-1.20217254e-03  4.26050737e-04  1.00000000e+00]]
Determinant of Normalized H: 0.022777336231365287


# Step 5 & 6

In [158]:
import cv2
import numpy as np
import pickle
import os
import tkinter as tk
from tkinter import filedialog
from PIL import Image, ImageTk

class ImageProcessor:
    def __init__(self, root):
        self.root = root
        self.root.title("Feature Matching & Homography")

        # Frame for buttons
        self.frame = tk.Frame(root)
        self.frame.pack()

        # Buttons
        self.load_ref_button = tk.Button(self.frame, text="Load Reference Image", command=self.load_reference_image)
        self.load_ref_button.pack(side=tk.LEFT)

        self.load_aerial_button = tk.Button(self.frame, text="Load Aerial Image", command=self.load_aerial_image)
        self.load_aerial_button.pack(side=tk.LEFT)

        self.compute_homography_button = tk.Button(self.frame, text="Compute Homography", command=self.compute_homography, state=tk.DISABLED)
        self.compute_homography_button.pack(side=tk.LEFT)


        # Canvas to display images
        self.canvas = tk.Canvas(root, width=800, height=600, bg="gray")
        self.canvas.pack()

        # Image variables
        self.reference_image = None
        self.aerial_image = None
        self.reference_keypoints = None
        self.reference_descriptors = None
        self.orb = cv2.ORB_create()
        self.clicked_point = None
        self.H = None  # Homography matrix

        # Bind mouse click event to capture pixel coordinates
        self.canvas.bind("<Button-1>", self.project_clicked_point)

    def load_reference_image(self):
        filepath = filedialog.askopenfilename(filetypes=[("TIFF files", "*.tif"), ("All files", "*.*")])
        if filepath:
            self.reference_image = cv2.imread(filepath, cv2.IMREAD_GRAYSCALE)
            self.display_image(self.reference_image)

            # Try loading precomputed keypoints and descriptors
            if os.path.exists("reference_features.pkl"):
                try:
                    with open("reference_features.pkl", "rb") as f:
                        data = pickle.load(f)
                        self.reference_keypoints = [cv2.KeyPoint(x, y, size) for x, y, size in data["keypoints"]]
                        self.reference_descriptors = data["descriptors"]
                    print("Loaded precomputed reference features.")
                    return
                except (EOFError, pickle.UnpicklingError):
                    print("Corrupted feature file detected. Recomputing...")

            # Compute and store features
            self.reference_keypoints, self.reference_descriptors = self.orb.detectAndCompute(self.reference_image, None)
            keypoints_serializable = [(kp.pt[0], kp.pt[1], kp.size) for kp in self.reference_keypoints]
            data = {"keypoints": keypoints_serializable, "descriptors": self.reference_descriptors}

            with open("reference_features.pkl", "wb") as f:
                pickle.dump(data, f)
            print("Computed and stored new reference features.")

    def load_aerial_image(self):
        filepath = filedialog.askopenfilename(filetypes=[("PNG files", "*.png"), ("All files", "*.*")])
        if filepath:
            aerial_img = cv2.imread(filepath, cv2.IMREAD_GRAYSCALE)

            # Resize aerial image to match reference image size
            if self.reference_image is not None:
                aerial_img = cv2.resize(aerial_img, (self.reference_image.shape[1], self.reference_image.shape[0]))

            self.aerial_image = aerial_img
            self.display_image(self.aerial_image)
            self.compute_homography_button.config(state=tk.NORMAL)  # Enable Compute Homography button

    def compute_homography(self):
        if self.aerial_image is None or self.reference_image is None:
            print("Please load both images first.")
            return

        # Compute keypoints & descriptors for aerial image
        aerial_keypoints, aerial_descriptors = self.orb.detectAndCompute(self.aerial_image, None)

        # Match descriptors using BFMatcher
        bf = cv2.BFMatcher(cv2.NORM_HAMMING, crossCheck=True)
        matches = bf.match(self.reference_descriptors, aerial_descriptors)
        matches = sorted(matches, key=lambda x: x.distance)  # Sort matches by distance

        # Use top N matches
        num_matches = 55  # Adjust as needed
        good_matches = matches[:num_matches]

        if len(good_matches) < 4:
            print("Not enough matches to compute homography.")
            return

        # Extract matched keypoints
        ref_pts = np.float32([self.reference_keypoints[m.queryIdx].pt for m in good_matches]).reshape(-1, 1, 2)
        aerial_pts = np.float32([aerial_keypoints[m.trainIdx].pt for m in good_matches]).reshape(-1, 1, 2)

        # Compute Homography using RANSAC
        H, mask = cv2.findHomography(aerial_pts, ref_pts, cv2.RANSAC, 15.0)
        H /= H[2, 2]  # Normalize
        print("Computed Homography Matrix:\n", H)
        print("Determinant of Normalized H:", np.linalg.det(H))

        self.H = H  # Store homography for later use

    def get_clicked_coordinates(self, event):
        """ Capture clicked pixel coordinates on aerial image """
        if self.aerial_image is None:
            return
        self.clicked_point = (event.x, event.y)
        print(f"Clicked Pixel on Aerial Image: {self.clicked_point}")

    def project_clicked_point(self, event):
        """ Handles mouse click on aerial image and projects the clicked point to the reference image. """
        x, y = event.x, event.y  # Clicked pixel in aerial image
    
        # Ensure homography is computed
        if not hasattr(self, 'H') or self.H is None:
            print("Error: Homography matrix not computed.")
            return
    
        # Project the point
        result = self.project_point(x, y)
    
        if result:
            projected_x, projected_y, lat, lon = result  # ✅ Unpack correctly
            print(f"Clicked at ({x}, {y}) → Projected at ({projected_x}, {projected_y}) → Lat/Lon: ({lat}, {lon})")

    def pixel_to_geo(self, px, py):
        """ Converts reference image pixel (px, py) to latitude & longitude using interpolation. """
        
        # Example values - replace with actual min/max lat/lon of reference image
        lat_min, lat_max = 30.0, 30.5  # Replace with actual latitude range
        lon_min, lon_max = 70.0, 70.5  # Replace with actual longitude range
        img_h, img_w = self.reference_image.shape[:2]  # Get reference image size
    
        # Step 1: Normalize pixel coordinates to [0,1] range
        norm_x = px / img_w
        norm_y = py / img_h
    
        # Step 2: Scale to geographic coordinates
        latitude = lat_min + (lat_max - lat_min) * norm_y
        longitude = lon_min + (lon_max - lon_min) * norm_x
    
        return latitude, longitude


    
    def project_point(self, x, y):
        """ Projects a pixel from aerial image to reference image using Homography matrix 
            and converts it to latitude & longitude.
        """
        if not hasattr(self, 'H') or self.H is None:
            print("Homography matrix not computed yet.")
            return None
    
        # Step 1: Apply Homography transformation
        point = np.array([[x, y, 1]], dtype=np.float32).T  # Convert to homogeneous coordinates
        projected_point = np.dot(self.H, point)
        projected_point /= projected_point[2, 0]  # Normalize properly
    
        # Get pixel coordinates in the reference image
        proj_x, proj_y = int(projected_point[0, 0]), int(projected_point[1, 0])
    
        # Step 2: Convert (proj_x, proj_y) to Latitude and Longitude
        lat, lon = self.pixel_to_geo(proj_x, proj_y)
    
        print(f"Projected Pixel: ({proj_x}, {proj_y}) → Latitude: {lat}, Longitude: {lon}")
    
        return proj_x, proj_y, lat, lon  # Return all values


    def display_image(self, image):
        """ Convert OpenCV image to Tkinter-compatible format and display it """
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB) if len(image.shape) == 3 else cv2.cvtColor(image, cv2.COLOR_GRAY2RGB)
        image = Image.fromarray(image)

        # Resize only if the image is too large for the canvas
        img_width, img_height = image.size
        canvas_width, canvas_height = 800, 600

        if img_width > canvas_width or img_height > canvas_height:
            scale = min(canvas_width / img_width, canvas_height / img_height)
            new_size = (int(img_width * scale), int(img_height * scale))
            image = image.resize(new_size, Image.Resampling.LANCZOS)

        self.tk_image = ImageTk.PhotoImage(image)
        self.canvas.create_image(0, 0, anchor=tk.NW, image=self.tk_image)

# Run the application
root = tk.Tk()
app = ImageProcessor(root)
root.mainloop()


Loaded precomputed reference features.
Computed Homography Matrix:
 [[-3.13049617e-01 -2.02936362e+00  7.84516206e+03]
 [ 1.20735655e+00  8.28069067e-03 -1.58864121e+03]
 [ 5.75145398e-04 -5.59573717e-04  1.00000000e+00]]
Determinant of Normalized H: -0.757502770894568
Projected Pixel: (6916, -1126) → Latitude: 29.860158966716345, Longitude: 70.85891703924491
Clicked at (367, 351) → Projected at (6916, -1126) → Lat/Lon: (29.860158966716345, 70.85891703924491)


In [160]:
import cv2
import numpy as np
import tkinter as tk
from tkinter import filedialog
from PIL import Image, ImageTk

class ImageProcessor:
    def __init__(self, root):
        self.root = root
        self.root.title("Feature Matching & Homography")

        # Frame for buttons
        self.frame = tk.Frame(root)
        self.frame.pack()

        # Buttons
        self.load_ref_button = tk.Button(self.frame, text="Load Reference Image", command=self.load_reference_image)
        self.load_ref_button.pack(side=tk.LEFT)

        self.load_aerial_button = tk.Button(self.frame, text="Load Aerial Image", command=self.load_aerial_image)
        self.load_aerial_button.pack(side=tk.LEFT)

        self.compute_homography_button = tk.Button(self.frame, text="Compute Homography", command=self.compute_homography, state=tk.DISABLED)
        self.compute_homography_button.pack(side=tk.LEFT)

        # Canvas to display images
        self.canvas = tk.Canvas(root, width=800, height=600, bg="gray")
        self.canvas.pack()

        # Image variables
        self.reference_image = None
        self.aerial_image = None
        self.reference_keypoints = None
        self.reference_descriptors = None
        self.sift = cv2.SIFT_create()
        self.clicked_point = None
        self.H = None  # Homography matrix

        # Bind mouse click event
        self.canvas.bind("<Button-1>", self.project_clicked_point)

    def load_reference_image(self):
        filepath = filedialog.askopenfilename(filetypes=[("TIFF files", "*.tif"), ("All files", "*.*")])
        if filepath:
            self.reference_image = cv2.imread(filepath, cv2.IMREAD_GRAYSCALE)
            self.display_image(self.reference_image)

            # Compute fresh SIFT features
            self.reference_keypoints, self.reference_descriptors = self.sift.detectAndCompute(self.reference_image, None)
            print("Computed new reference features.")

    def load_aerial_image(self):
        filepath = filedialog.askopenfilename(filetypes=[("PNG files", "*.png"), ("All files", "*.*")])
        if filepath:
            aerial_img = cv2.imread(filepath, cv2.IMREAD_GRAYSCALE)

            # Resize aerial image to match reference image size
            if self.reference_image is not None:
                aerial_img = cv2.resize(aerial_img, (self.reference_image.shape[1], self.reference_image.shape[0]))

            self.aerial_image = aerial_img
            self.display_image(self.aerial_image)
            self.compute_homography_button.config(state=tk.NORMAL)

    def compute_homography(self):
        if self.aerial_image is None or self.reference_image is None:
            print("Please load both images first.")
            return

        # Compute SIFT features for aerial image
        aerial_keypoints, aerial_descriptors = self.sift.detectAndCompute(self.aerial_image, None)

        # Use BFMatcher with kNN
        bf = cv2.BFMatcher()
        matches = bf.knnMatch(self.reference_descriptors, aerial_descriptors, k=2)

        # Apply Lowe's ratio test
        good_matches = []
        for m, n in matches:
            if m.distance < 0.75 * n.distance:
                good_matches.append(m)

        if len(good_matches) < 4:
            print("Not enough good matches to compute homography.")
            return

        # Extract matched keypoints
        ref_pts = np.float32([self.reference_keypoints[m.queryIdx].pt for m in good_matches]).reshape(-1, 1, 2)
        aerial_pts = np.float32([aerial_keypoints[m.trainIdx].pt for m in good_matches]).reshape(-1, 1, 2)

        # Compute Homography using RANSAC
        H, mask = cv2.findHomography(aerial_pts, ref_pts, cv2.RANSAC, 10.0)
        print("Computed Homography Matrix:\n", H)
        print("Determinant of Normalized H:", np.linalg.det(H))

        self.H = H  # Store homography for later use

    def project_clicked_point(self, event):
        """ Handles mouse click on aerial image and projects to reference image. """
        x, y = event.x, event.y  # Clicked pixel in aerial image

        if self.H is None:
            print("Error: Homography matrix not computed.")
            return

        # Apply Homography transformation
        point = np.array([[x, y, 1]], dtype=np.float32).T  # Convert to homogeneous coordinates
        projected_point = np.dot(self.H, point)
        projected_point /= projected_point[2, 0]  # Normalize

        # Get pixel coordinates in the reference image
        proj_x, proj_y = int(projected_point[0, 0]), int(projected_point[1, 0])

        # Convert to latitude & longitude
        lat, lon = self.pixel_to_geo(proj_x, proj_y)

        print(f"Clicked at ({x}, {y}) → Projected at ({proj_x}, {proj_y}) → Lat/Lon: ({lat}, {lon})")

        # Show reference image with the marked point
        self.show_marked_reference_image(proj_x, proj_y, lat, lon)

    def show_marked_reference_image(self, x, y, lat, lon):
        """ Displays the reference image with the marked projected point. """
        if self.reference_image is None:
            print("Error: Reference image not loaded.")
            return

        img_h, img_w = self.reference_image.shape[:2]
        x = max(0, min(img_w - 1, int(x)))  # Clamp within bounds
        y = max(0, min(img_h - 1, int(y)))

        # Convert grayscale to BGR for marking
        marked_image = cv2.cvtColor(self.reference_image.copy(), cv2.COLOR_GRAY2BGR)

        # Draw point
        cv2.circle(marked_image, (x, y), radius=6, color=(0, 255, 0), thickness=-1)

        # Put lat/lon text
        coord_text = f"{lat:.5f}, {lon:.5f}"
        cv2.putText(marked_image, coord_text, (x + 10, y - 10),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 2, cv2.LINE_AA)

        # Show marked image
        cv2.imshow("Projected Point on Reference Image", marked_image)
        cv2.waitKey(0)
        cv2.destroyAllWindows()

    def pixel_to_geo(self, px, py):
        """ Converts reference image pixel (px, py) to latitude & longitude. """
        lat_min, lat_max = 30.0, 30.5
        lon_min, lon_max = 70.0, 70.5
        img_h, img_w = self.reference_image.shape[:2]

        norm_x = px / img_w
        norm_y = py / img_h

        latitude = lat_min + (lat_max - lat_min) * norm_y
        longitude = lon_min + (lon_max - lon_min) * norm_x

        return latitude, longitude

    def display_image(self, image):
        """ Convert OpenCV image to Tkinter-compatible format and display it without zooming in. """
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB) if len(image.shape) == 3 else cv2.cvtColor(image, cv2.COLOR_GRAY2RGB)
        image = Image.fromarray(image)
    
        # Fixed canvas size (adjust as needed)
        canvas_width, canvas_height = 800, 600  # Change these values if needed
    
        # Get original image size
        img_width, img_height = image.size
    
        # Resize only if the image is too large for the canvas
        if img_width > canvas_width or img_height > canvas_height:
            scale = min(canvas_width / img_width, canvas_height / img_height)  # Scale factor
            new_size = (int(img_width * scale), int(img_height * scale))
            image = image.resize(new_size, Image.Resampling.LANCZOS)  # Maintain quality
    
        # Update canvas size to fixed values
        self.canvas.config(width=canvas_width, height=canvas_height)
        self.canvas.delete("all")  # Clear previous image
    
        self.tk_image = ImageTk.PhotoImage(image)
        self.canvas.create_image(0, 0, anchor=tk.NW, image=self.tk_image)

# Run the application
root = tk.Tk()
app = ImageProcessor(root)
root.mainloop()


Computed new reference features.
Computed Homography Matrix:
 [[-1.20580234e+00 -4.22750598e-01  3.06980941e+03]
 [-1.32619959e+00 -7.03152306e-01  4.04604709e+03]
 [-3.82062017e-04 -1.56599254e-04  1.00000000e+00]]
Determinant of Normalized H: -0.010443520719706167
Clicked at (512, 222) → Projected at (3064, 4172) → Lat/Lon: (30.518132141082962, 70.38052657724789)
